name: Trigger auto deployment for oteltestapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '/docker/**'
    - '.github/workflows/oteltestapp-AutoDeployTrigger-c54b0cda-2897-450e-9e9d-6124c7f87eb2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OTELTESTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/MyDotnetApp
          dockerfilePath: ${{ github.workspace }}/docker/dev.Dockerfile
          registryUrl: snehapark4apssacr.azurecr.io
          registryUsername: ${{ secrets.OTELTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OTELTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: oteltestapp
          resourceGroup: ca-snehapar-group
          imageToBuild: snehapark4apssacr.azurecr.io/oteltestapp:${{ github.sha }}
          
            

     

