name: Trigger auto deployment for sourcecontrolapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sourcecontrolapp-AutoDeployTrigger-f1f121aa-f8c6-4723-b776-1f2110d952aa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SOURCECONTROLAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SOURCECONTROLAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SOURCECONTROLAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: snehapark4apssacr.azurecr.io
          registryUsername: ${{ secrets.SOURCECONTROLAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SOURCECONTROLAPP_REGISTRY_PASSWORD }}
          containerAppName: sourcecontrolapp
          resourceGroup: EnvTest
          imageToBuild: snehapark4apssacr.azurecr.io/sourcecontrolapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


